name: Python Application CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the build

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Set the Python version to use

    # Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests (if you have any)
    - name: Run tests
      run: |
        pytest  # or any other testing command you use

    # Deploy step (optional)
    - name: Deploy to production (optional)
      run: |
        # Add deployment commands here (e.g., using SSH, Docker, etc.)
        echo "Deploying to production..."  # Example placeholder
        # For example, you can deploy to a server or cloud platform
